// <auto-generated />
using System;
using Internship_13_MovieRadar.Data.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Internship_13_MovieRadar.Data.Migrations
{
    [DbContext(typeof(MovieRadarDbContext))]
    [Migration("20250210111918_AddConstraintInTitle")]
    partial class AddConstraintInTitle
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Internship_13_MovieRadar.Data.Entities.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ReleaseYear")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("Title")
                        .IsUnique();

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = new Guid("569db240-3a29-4a3e-a276-b49b1c74a124"),
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 127, DateTimeKind.Local).AddTicks(1075),
                            Description = "A thief who steals corporate secrets through dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            Genre = "Sci-Fi",
                            ImageUrl = "",
                            ReleaseYear = 2010,
                            Title = "Inception"
                        },
                        new
                        {
                            Id = new Guid("bb9b69e3-0933-4a5c-b4de-e4f072207582"),
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 127, DateTimeKind.Local).AddTicks(6015),
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            Genre = "Drama",
                            ImageUrl = "",
                            ReleaseYear = 1994,
                            Title = "The Shawshank Redemption"
                        },
                        new
                        {
                            Id = new Guid("a24ef457-9d04-412f-a0bd-a89f5e790ca8"),
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 127, DateTimeKind.Local).AddTicks(6108),
                            Description = "When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.",
                            Genre = "Action",
                            ImageUrl = "",
                            ReleaseYear = 2008,
                            Title = "The Dark Knight"
                        });
                });

            modelBuilder.Entity("Internship_13_MovieRadar.Data.Entities.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("MovieId")
                        .HasColumnType("uuid");

                    b.Property<int>("Rating")
                        .HasColumnType("integer")
                        .HasAnnotation("Range", new[] { 1, 5 });

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId", "MovieId")
                        .IsUnique();

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d65d3c55-811d-4404-9af0-31d973b7d3a5"),
                            Content = "Complex plot but very entertaining. The visual effects are stunning.",
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 127, DateTimeKind.Local).AddTicks(9593),
                            MovieId = new Guid("569db240-3a29-4a3e-a276-b49b1c74a124"),
                            Rating = 4,
                            UserId = new Guid("39f22297-9a28-45a8-906e-b7866d1317de")
                        },
                        new
                        {
                            Id = new Guid("6259b7c5-0739-42e5-9de1-c888bc096895"),
                            Content = "A timeless classic. Morgan Freeman's performance is outstanding.",
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 128, DateTimeKind.Local).AddTicks(3914),
                            MovieId = new Guid("bb9b69e3-0933-4a5c-b4de-e4f072207582"),
                            Rating = 5,
                            UserId = new Guid("39f22297-9a28-45a8-906e-b7866d1317de")
                        },
                        new
                        {
                            Id = new Guid("309ca33f-c2a2-4174-ac28-8ed603fac02c"),
                            Content = "One of the greatest movies ever made. The story is deeply moving.",
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 128, DateTimeKind.Local).AddTicks(4288),
                            MovieId = new Guid("bb9b69e3-0933-4a5c-b4de-e4f072207582"),
                            Rating = 5,
                            UserId = new Guid("c7da352e-9fc4-46ef-8c30-dfb39fd11473")
                        },
                        new
                        {
                            Id = new Guid("c4b0e4ca-36ba-4dec-bd85-75db10ad0bbb"),
                            Content = "Heath Ledger's Joker is unforgettable. A perfect superhero movie.",
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 128, DateTimeKind.Local).AddTicks(4302),
                            MovieId = new Guid("a24ef457-9d04-412f-a0bd-a89f5e790ca8"),
                            Rating = 5,
                            UserId = new Guid("c7da352e-9fc4-46ef-8c30-dfb39fd11473")
                        },
                        new
                        {
                            Id = new Guid("76a681d8-906d-4f02-a719-ed58ba131c4a"),
                            Content = "Brilliant direction by Nolan. The pacing and action scenes are incredible.",
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 128, DateTimeKind.Local).AddTicks(4312),
                            MovieId = new Guid("a24ef457-9d04-412f-a0bd-a89f5e790ca8"),
                            Rating = 4,
                            UserId = new Guid("744d3d7c-6cec-4dbb-9173-74abed06db44")
                        },
                        new
                        {
                            Id = new Guid("f073d929-2f28-45a4-b564-5dd25f0d0bf8"),
                            Content = "The ending left me questioning everything. Great soundtrack too.",
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 128, DateTimeKind.Local).AddTicks(4320),
                            MovieId = new Guid("569db240-3a29-4a3e-a276-b49b1c74a124"),
                            Rating = 4,
                            UserId = new Guid("744d3d7c-6cec-4dbb-9173-74abed06db44")
                        });
                });

            modelBuilder.Entity("Internship_13_MovieRadar.Data.Entities.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ab00e0ac-3865-44bb-8e27-b109ebfa5346"),
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 113, DateTimeKind.Local).AddTicks(9464),
                            Email = "admin@movieradar.com",
                            FirstName = "Admin",
                            IsAdmin = true,
                            LastName = "User",
                            Password = "oQnjaUetVt4dyhzEnw74rJrZp7GqDfQfs8TLc8H/Aeo="
                        },
                        new
                        {
                            Id = new Guid("39f22297-9a28-45a8-906e-b7866d1317de"),
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 124, DateTimeKind.Local).AddTicks(6853),
                            Email = "john.doe@gmail.com",
                            FirstName = "John",
                            IsAdmin = false,
                            LastName = "Doe",
                            Password = "qErJCXpDKt4m+zyvP95FuukV3gEGrD1so8mCtoZtMcE="
                        },
                        new
                        {
                            Id = new Guid("c7da352e-9fc4-46ef-8c30-dfb39fd11473"),
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 124, DateTimeKind.Local).AddTicks(7021),
                            Email = "jane.smith@gmail.com",
                            FirstName = "Jane",
                            IsAdmin = false,
                            LastName = "Smith",
                            Password = "qFYB54kbXvV24+kUz/cJy2WVfl9ifGPtY5t3plLC1YY="
                        },
                        new
                        {
                            Id = new Guid("744d3d7c-6cec-4dbb-9173-74abed06db44"),
                            CreatedAt = new DateTime(2025, 2, 10, 12, 19, 17, 124, DateTimeKind.Local).AddTicks(7033),
                            Email = "mark.wilson@gmail.com",
                            FirstName = "Mark",
                            IsAdmin = false,
                            LastName = "Wilson",
                            Password = "qFYB54kbXvV24+kUz/cJy2WVfl9ifGPtY5t3plLC1YY="
                        });
                });

            modelBuilder.Entity("Internship_13_MovieRadar.Data.Entities.Models.Review", b =>
                {
                    b.HasOne("Internship_13_MovieRadar.Data.Entities.Models.Movie", "Movie")
                        .WithMany("Reviews")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Internship_13_MovieRadar.Data.Entities.Models.User", "User")
                        .WithMany("Reviews")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Internship_13_MovieRadar.Data.Entities.Models.Movie", b =>
                {
                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Internship_13_MovieRadar.Data.Entities.Models.User", b =>
                {
                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
