CREATE TABLE Users (
    Id UUID PRIMARY KEY,
    Email TEXT NOT NULL UNIQUE,
    Password TEXT NOT NULL,
    FirstName TEXT NOT NULL,
    LastName TEXT NOT NULL,
    IsAdmin BOOLEAN NOT NULL DEFAULT FALSE,
    CreatedAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW()
);

CREATE TABLE Movies (
    Id UUID PRIMARY KEY,
    Title TEXT NOT NULL UNIQUE,
    Description TEXT NOT NULL,
    Genre TEXT NOT NULL,
    ReleaseYear INT NOT NULL,
    ImageUrl TEXT,
    CreatedAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    UpdatedAt TIMESTAMP WITHOUT TIME ZONE
);

CREATE TABLE Reviews (
    Id UUID PRIMARY KEY,
    UserId UUID NOT NULL,
    MovieId UUID NOT NULL,
    Content TEXT NOT NULL,
    Rating INT NOT NULL CHECK (Rating BETWEEN 1 AND 5),
    CreatedAt TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT NOW(),
    CONSTRAINT fk_reviews_user FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
    CONSTRAINT fk_reviews_movie FOREIGN KEY (MovieId) REFERENCES Movies(Id) ON DELETE CASCADE,
    CONSTRAINT unique_user_movie_review UNIQUE (UserId, MovieId)
);
